### DISCUSSION TITLE
Please add phpmyadmin

### DISCUSSION THREAD

**Discussion by DanooTech** [NiclasvanEyk/initializer-for-laravel#81] [Ideas]
Can you make an option for phpmyadmin?

For the docker-compose.yml:
```
phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mysql:mysql
        ports:
          - 8080:80
        environment:
          MYSQL_USERNAME: "${DB_USERNAME}"
          MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
          PMA_HOST: mysql
        networks:
            - sail
```
